export const privacyData = {
  privacyPolicy: {
    title: 'Privacy Policy',
    st1: 'This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.',
    st2: 'We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.',
  },
  interpretationsDefinitons: {
    title: 'Interpretations And Definitions',
    ht1: 'Interpretation',
    st1: 'The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.',
    ht2: 'Defiinitions',
    st2: 'For the purposes of this Privacy Policy:',
    stbp: [
      `Account means a unique account created for You to access our Service or parts of our Service.`,
      `Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Hush UX Agency, LLC, Floor 3, Rave Towers, Pawpaw Street, East Legon, GA, Ghana 00233.`,
      `Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.`,
      'Country refers to: Greater Accra, Ghana',
      `Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.`,
      `Personal Data is any information that relates to an identified or identifiable individual.`,
      `Service refers to the Website.`,
      `Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.`,
      `Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).`,
      `Website refers to Hush UX, accessible from https://hushux.com/`,
      `You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.`,
    ],
  },
  collectingUsingYourPersonalData: {
    title: 'Collecting and Using Your Personal Data',
    ht1: 'Types of Data Collected',
    sht1: 'Personal Data',
    shtst1:
      'While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:',
    sht2: ['Usage Data'],
    sht2st1: [
      `Usage Data is collected automatically when using the Service.`,
      `Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.`,
      `When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.`,
      `We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.`,
    ],
    sht3: 'Tracking Technologies and Cookies',
  },
};
